### ISSUE TITLE
Bug in YML File

### ISSUE THREAD

**Issue by JEEVAN28** [dhananjay1405/tally-database-loader#30] opened 2024-04-19 05:05 UTC
Hi, 

I noticed error in YML file related to trn_batch

Code is
- name: name
          field: Name
          type: text

and required is
- name: name
          field: batchName
          type: text

Regards
Jeevan Pendhari

**Comment by dhananjay1405** [comment] 2024-04-20 04:02
@JEEVAN28 A good observation. For me while testing all the batch name values came as "Primary Batch" instead of blank, when I substituted name with BatchName field. A thought came to my mind if I should remove this field totally as it is not giving any distinguishing information. I am integrating changes suggested by you in the next release.

But do share your thoughts on the discussion, if we can plan of removing this field, if found unnecessary. I will appreciate if you could run few tests on your data, post release of this fix to determine this.

**Comment by dhananjay1405** [comment] 2024-04-22 16:54
Fixed in c5b38b21c1a9bac4855d3a75dff87a07101f4099

**Comment by dhananjay1405** [comment] 2024-04-23 06:41
@JEEVAN28 it is indeed a good suggestion. But the issue is, YAML structure will become even more complicated, since for each field, one more line of Yes/No would get added. Many people have been asking for an easy way to modify YAML file, as any error while modification of YAML leads to malformed XML generated by utility, which crashes tally.exe process (even happens with me sometimes when I break YAML structure mistakenly while adding / removing fields).

**Comment by dhananjay1405** [comment] 2024-04-23 06:56
@JEEVAN28 it is indeed a good suggestion. But the issue is, YAML structure will become even more complicated, since for each field, one more line of Yes/No would get added. Also, database structure needs to be kept in sync on these lines, which makes it difficult to manage. Many people have been asking for an easy way to modify YAML file, as any error while modification of YAML leads to malformed XML generated by utility, which crashes tally.exe process (even happens with me sometimes when I break YAML structure mistakenly while adding / removing fields).

I am converting this discussion to feature request (which was been suggestion from long time), that some webpage needs to be developed for managing YAML file with following functionality:
1. Functionality to add / remove tables (or collections of Tally)
2. Functionality to add / remove fields of Tally
3. Dropdown of for in-built Tally Collections / Fields available in official Tally Database schema model.

I have re-opened this thread and will keep it open for suggestion. This thread would also serve me as reminder, that this feature is pending.

**Comment by JEEVAN28** [comment] 2024-04-24 09:12
Hi,

What I am suggesting is that, in case tag is not mentioned then default
value should be Yes

Regards
Jeevan Pendhari

**Comment by dhananjay1405** [comment] 2024-04-24 13:35
@JEEVAN28 ok I get your point now. I am not sure if I can parse conditional property (or tag) in YAML, but definitely I will give this a try. After many years of experimentation and testing, the YAML structure and utility code has moved to stable stage. So, I want to carefully weigh any new changes in YAML structure, without risking stability of code. I know many people who are now getting familiar with functioning of YAML file & have modified it for their own organization. That is the main reason, I am thinking of playing with YAML file externally from webpage to manipulate and manage it, instead of utility code, which is quite safe.

Going forward once incremental sync (and few pending features like a Graphical Interface) stabilizes , I might even freeze code base of this project.

**Comment by dhananjay1405** [comment] 2024-09-09 17:34
Merging this thread into feature request discussion #32

**Closed by dhananjay1405** 2024-09-09 17:34 UTC
